@startuml VacQ System Use Case Diagram
left to right direction
actor "User" as user
rectangle "Dentist Booking System" as VacQSystem {    
    usecase "Login" as login
    usecase "Logout" as logout
    usecase "Register" as register
    usecase "View\nMy Profile" as viewUserProfile
    usecase "View\nClinics" as viewClinics
    usecase "View\nDentists" as viewDentists
    usecase "Manage\nDentist" as manageDentist
    usecase "View\nAppointments" as viewAppt
    usecase "Manage\nAppointment" as manageAppt
}

user -- register
user -- login
user -- logout
user -- viewUserProfile
user -- viewClinics
user -- viewDentists
user -- viewAppt
user -- manageAppt

actor "Admin" as admin
register -- admin
login -- admin
logout -- admin
viewUserProfile -- admin
viewClinics -- admin
viewDentists -- admin
manageDentist -- admin
viewAppt -- admin
manageAppt -- admin

@enduml