@startuml VacQ System Use Case Diagram
left to right direction
actor "User" as user
rectangle "Dentist Booking System" as VacQSystem {    
    usecase "Login" as login
    usecase "Logout" as logout
    usecase "Register" as register
    usecase "View\nOwn Profile" as viewUserProfile
    usecase "View\nClinics" as viewClinics
    usecase "View\nDentists" as viewDentists
    usecase "Manage\nDentist" as manageDentist
    usecase "View\nAll Appointments" as viewAllAppt
    usecase "View\nOwn Appointments" as viewOwnAppt
    usecase "Manage\n All Appointment" as manageAllAppt
    usecase "Manage\nOwn Appointment" as manageOwnAppt
}

user -- register
user -- login
user -- logout
user -- viewUserProfile
user -- viewClinics
user -- viewDentists
user -- viewOwnAppt
user -- manageOwnAppt

actor "Admin" as admin
register -- admin
login -- admin
logout -- admin
viewUserProfile -- admin
viewClinics -- admin
viewDentists -- admin
manageDentist -- admin
viewAllAppt -- admin
manageAllAppt -- admin

@enduml