@startuml
left to right direction
package "Dentist Booking System"{
    class "<<Application>>\nDentist Booking Service" as DentistBookingService{}

' dentists
    class "<<Resource>>\nDentists" as ResourceDentists{
        <<GET>> +getDentists(): Destist
        <<POST>> +createDentist(): Dentist
    }

    class "<<Resource>>\nDentist" as ResourceDentist {
        <<GET>> +getDentist(): Dentist
        <<PUT>> +updateDentist(): Dentist
        <<DELETE>> +deleteDentist(): void
    }

    class "<<Representation>>\nDentist" as RepresentationDentist {
        -name
        -yearOfExp
        -areaOfExpertise
        -clinic
    }

    ' auth
    class "<<Resource>>Auth" as ResourceAuth{
        
    }
    class "<<Resource>>Register" as ResourceUserRegister{
        <<POST>> +register(): User
    }
    class "<<Resource>>Login" as ResourceUserLogin{
        <<POST>> +login(): User
    }
    class "<<Resource>>User" as ResourceUser{
        <<GET>> +me(): User
    }
    class "<<Resource>>Logout" as ResourceUserLogout{
        <<GET>> +logout(): void
    }
    class "<<Representation>>\nUser" as RepresentationUser {
        -name
        -tel
        -email
        -password
        -role
    }

    ' clinic
    class "<<Resource>>Clinics" as ResourceClinics{
        <<GET>> +getClinics(): Clinic
    } 
    class "<<Representation>>\nClinic" as RepresentationClinic {
        -name
        -address
        -district
        -province
        -postalcode
        -tel
        -region
    }

    ' appointment
    class "<<Resource>>\nAppointments" as ResourceAppointments{
        <<GET>> +getAppointments(): Appointment
    }
    class "<<Resource>>\nAppointment" as ResourceAppointment{
        <<GET>> +getAppointment(): Appointment
        <<PUT>> +updateAppointment(): Appointment
        <<DELETE>> +deleteAppointment(): void
    }
     class "<<Resource>>\nDentistAppointments" as ResourceDentistAppointments{
        <<POST>> +addAppointment(): Appointment
    } 
    class "<<Representation>>\nAppointment" as RepresentationAppointment {
        -apptDate
        -user
        -dentist
        -createdAt
    }

}

DentistBookingService ..> ResourceDentists:"/dentists\n<<Path>>"
ResourceDentists ..> ResourceDentist: "/{dentistId}\n<<Path>>"
ResourceDentist ..> RepresentationDentist: "<<use>>"
ResourceDentist ..> ResourceDentistAppointments:"/reviews\n<<Path>>"
ResourceDentistAppointments..>RepresentationAppointment:"<<use>>"

DentistBookingService..>ResourceAuth:"/auth\n<<Path>>"
ResourceAuth..> ResourceUserRegister: "/register\n<<Path>>"
ResourceUserRegister ..>RepresentationUser: "<<use>>"
ResourceAuth ..> ResourceUserLogin: "/login\n<<Path>>"
ResourceUserLogin ..>RepresentationUser: "<<use>>"
ResourceAuth ..> ResourceUser: "/me\n<<Path>>"
ResourceUser ..>RepresentationUser: "<<use>>"
ResourceAuth ..> ResourceUserLogout: "/logout\n<<Path>>"

DentistBookingService ..> ResourceClinics:"/clinics\n<<Path>>"
ResourceClinics ..> RepresentationClinic:"<<use>>"

DentistBookingService ..> ResourceAppointments:"/appointments\n<<Path>>"
ResourceAppointments ..> ResourceAppointment: "/{appointmentId}\n<<Path>>"
ResourceAppointment ..> RepresentationAppointment: "<<use>>"
@enduml